[package]
name = "bench-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
blstrs = "0.7"
blake3 = "1"
criterion = "0.5"
rand = "0.8"
ff = "0.13"

[[bench]]
name = "comparison"
harness = false
